package UI;

import DAO.ChatLieuDao;
import Entity.ChatLieu;
import Entity.TheLoai;
import Helper.MsgBox;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class ChatLieuUI extends javax.swing.JFrame {
    
    ChatLieuDao daocl = new ChatLieuDao();
    DefaultTableModel model;
    int row = 0;
    
    public ChatLieuUI() {
        initComponents();
        setLocationRelativeTo(null);
        defaullform();
        prepareGui();
        filltable();
        this.txtmachatlieu.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        JPanel1 = new javax.swing.JPanel();
        txttimkiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblchatlieu = new javax.swing.JTable();
        lblmachatlieu = new javax.swing.JLabel();
        txtmachatlieu = new javax.swing.JTextField();
        lbltenchatlieu = new javax.swing.JLabel();
        txttenchatlieu = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Chất Liệu");

        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });
        txttimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimkiemKeyReleased(evt);
            }
        });

        tblchatlieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã chất liệu", "Tên chất liệu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblchatlieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblchatlieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblchatlieu);

        lblmachatlieu.setText("Mã Chất Liệu");

        lbltenchatlieu.setText("Tên chất liệu");

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnclear.setText("Mới");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        jLabel1.setText("Tìm kiếm");

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmachatlieu)
                    .addComponent(lbltenchatlieu))
                .addGap(13, 13, 13)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnthem)
                        .addGap(18, 18, 18)
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmachatlieu, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(txttenchatlieu))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmachatlieu)
                    .addComponent(txtmachatlieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltenchatlieu)
                    .addComponent(txttenchatlieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnclear))
                .addGap(25, 25, 25)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabs.addTab("Danh Sách", JPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed
        timkiem();
    }//GEN-LAST:event_txttimkiemActionPerformed

    private void tblchatlieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblchatlieuMouseClicked
        if (evt.getClickCount() == 1) {
            tabs.setSelectedIndex(0);
            row = tblchatlieu.getSelectedRow();
            setform(daocl.selectByID(tblchatlieu.getValueAt(row, 0).toString()));
            updateStatus();
        }
    }//GEN-LAST:event_tblchatlieuMouseClicked

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        if (checknull()) {
            return;
        }
        them();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        clear();
    }//GEN-LAST:event_btnclearActionPerformed

    private void txttimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyReleased
      
    }//GEN-LAST:event_txttimkiemKeyReleased

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        sua();
    }//GEN-LAST:event_btnsuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatLieuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatLieuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatLieuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatLieuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatLieuUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblmachatlieu;
    private javax.swing.JLabel lbltenchatlieu;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblchatlieu;
    private javax.swing.JTextField txtmachatlieu;
    private javax.swing.JTextField txttenchatlieu;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables

    private void filltable() {
        DefaultTableModel model = (DefaultTableModel) tblchatlieu.getModel();
        ArrayList<ChatLieu> listchatlieu = daocl.selectAll();
        model.setRowCount(0);
        try {
            for (ChatLieu cl : listchatlieu) {
                model.addRow(new Object[]{cl.getMaChatLieu(), cl.getTenChatLieu()});
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vẫn dữ liệu");
        }
        
    }
    
    void timkiem() {
       ArrayList<ChatLieu> listTheLoai = daocl.selectAll();
       model.setRowCount(0);
        for (ChatLieu x : listTheLoai) {
            if(x.getMaChatLieu().toString().contains(txttimkiem.getText().trim()) || x.getTenChatLieu().toString().contains(txttimkiem.getText().trim())){
                model.addRow(new Object[]{
                    x.getMaChatLieu(),
                    x.getTenChatLieu(),
                });
            }
        }
    
    }
    
    void prepareGui() {
        String[] h = {"Mã chất liệu", "Tên chất liệu"};
        model = new DefaultTableModel(h, 0) {
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }
        };
    }

    void setform(ChatLieu cl) {
        txtmachatlieu.setText(cl.getMaChatLieu());
        txttenchatlieu.setText(cl.getTenChatLieu());
    }

    void defaullform() {
        row = -1;
        txtmachatlieu.setText("");
        txttenchatlieu.setText("");
        btnsua.setEnabled(false);
    }

    void updateStatus() {
        boolean click = row >= 0;
        btnsua.setEnabled(click);
        txtmachatlieu.setEnabled(!click);
        
    }
    
    private void them() {
        ChatLieu cl = getform();
        try {
            daocl.them(cl);
            filltable();
            MsgBox.alert(this, "Thêm chất liệu thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm chất liệu thất bại");
            e.printStackTrace();
        }
        
    }

    private void capnhat() {
        ChatLieu cl = getform();
        try {
            daocl.capNhat(cl);
            filltable();
            MsgBox.alert(this, "Cập nhật chất liệu thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật chất liệu thất bại");
            e.printStackTrace();
        }
    }
    
    private boolean checknull() {
        StringBuilder sb = new StringBuilder();
        if (txttenchatlieu.getText().equals("")) {
            sb.append("Bạn chưa nhập Tên chất liệu \n\n");
        }
        if (sb.length() > 0) {
            MsgBox.alert(this, sb.toString());
            return true;
        }
        return false;
    }
    
    public ChatLieu getform() {
        ChatLieu cl = new ChatLieu();
        cl.setMaChatLieu(txtmachatlieu.getText());
        cl.setTenChatLieu(txttenchatlieu.getText());
        return cl;
    }
    
    private void clear() {
        txtmachatlieu.setText("");
        txttenchatlieu.setText("");
        txtmachatlieu.setEnabled(true);
        btnsua.setEnabled(false);
    }
    
    private void sua() {
        
        if (MsgBox.confirm(this, "Bạn có muốn chỉnh sửa không không?")) {
            
        }
        daocl.capNhat(getform());
        filltable();
        defaullform();
        updateStatus();
        tabs.setSelectedIndex(0);
    }

    void xoa() {
        
        if (MsgBox.confirm(this, "Bạn có muốn xoá không?")) {
            daocl.xoa(txtmachatlieu.getText());
            filltable();
            defaullform();
            updateStatus();
            tabs.setSelectedIndex(2);
            
        }
    }
}
